kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'html-openshift-app:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
 
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "nginx:1.20-ubi7"
 
  postCommit: {}
 
  source:
    type: Git
    git:
      uri: "https://github.com/LinusBBW/Modul-210-K.git"
    contextDir: /auftrag6.2/Web
    sourceSecret:
      name: html-openshift-app-github
 
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: webhooksecret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
 
  runPolicy: Serial