kind: Secret
apiVersion: v1
metadata:
  name: webhooksecret
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  WebHookSecretKey: bXktc2VjcmV0LXZhbHVl
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-github
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  username: TGludXNCQlc=
  password: Z2hwX0lZTzA3eGFpcVFBYmJLeHhFSVg3MHpadlRXa3VwbTBjRFZDcg==
type: kubernetes.io/basic-auth
